name: "Just build"
on: [push]
jobs:
  run:
    name: Build
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        ocaml-version: ['4.08.1', '4.09.1']
    steps:
    - uses: actions/checkout@master

    - name: Setup OCaml
      uses: avsm/setup-ocaml@master
      with:
        ocaml-version: ${{ matrix.ocaml-version }}

    - run: opam pin add ocoi --no-action .
    - run: OPAMSOLVERTIMEOUT=3600 opam depext -yt ocoi
    - run: OPAMSOLVERTIMEOUT=3600 opam install -t . --deps-only
    - run: opam exec -- dune build
